ES: Mark rgb565d0s0ms0 as Android only
This prevents the following error from causing
cts-runner failures when testing es3/es31/es32

$ ./cts-runner --type=es3
Running OpenGL ES 3 conformance
No WGL configs enumerated: WGL is not supported on this OS
  found 8 compatible and 32 excluded configs
ERROR: No suitable configuration found for GL config rgb565d0s0ms0 at glcTestRunner.cpp:341

Signed-off-by: Robert Foss <robert.foss@collabora.com>