Fix Android standalone executables to work with EGL tests
Commit a34982063 (Support standalone executable builds on Android,
2024-09-12) added support for the DEQP_ANDROID_EXE option to build
standalone executables for Android.

The code was working well for Vulkan, but it was failing for EGL tests
with the following error:

-----------------------------------------------------------------------
Error: Failed to invoke dEQP for dEQP-EGL.info.extensions:
stdout:
Writing test log into /data/deqp/results/dEQP-EGL.info.extensions.qpa
dEQP Core opengl-es-cts-3.2.11.0-2-gc565b4b917c0cfabdd373a2a6ccc095205afa057 (0xc565b4b9) starting..
  target implementation = 'Android'
stderr:
FATAL ERROR: No factory supporting EGL 'display' type at egluUtil.cpp:549
-----------------------------------------------------------------------

This was due to the Platform::Platform(void) method added by the
mentioned change not calling some factory methods needed to set up the
EGL display and the GL context.

Fix this and also return NotSupportedError in
NativeWindowFactory::createWindow() so that windows test are ignored.

The fixes enable testing the Android EGL platform without having to go
via the Android activity manager.

Tests that render to native windows are unsupported, as command line
programs cannot create windows on Android.

This change is based on one from Tomeu used in mesa-ci and Antonio
Ospite has ported it to upstream VK-GL-CTS.

Signed-off-by: Tomeu Vizoso <tomeu@tomeuvizoso.net>
Signed-off-by: Antonio Ospite <antonio.ospite@collabora.com>

VK-GL-CTS issue: 5478

Components: Framework

Change-Id: I1bd6187f5e25f1d698f2a565ee610bbe94afc092