Fix warning introduced by 1.3 changes
Fixes the following warning in vktApiFeatureInfo.cpp, checkSupportFeatureBitInfluence was replaced by a generic function (checkApiVersionSupport<1,2>) in the changes to add 1.3 support.

.../external/vulkancts/modules/vulkan/api/vktApiFeatureInfo.cpp:1536:6: error: unused function 'checkSupportFeatureBitInfluence' [-Werror,-Wunused-function]
void checkSupportFeatureBitInfluence (Context& context)
     ^
1 error generated.

Components: Vulkan

VK-GL-CTS issue: 3132

Change-Id: Ia1996263f5a95730a50098c747c9f425c7e8a239