vulkancts: Include missing <cstdint>
Fixes build with gcc-13

../git/external/vulkancts/modules/vulkan/spirv_assembly/vktSpvAsmFloatControlsTests.cpp:2798:102: error: 'uintptr_t' in namespace 'std' does not name a type
 2798 |                 BufferDataType type              = static_cast<BufferDataType>(reinterpret_cast<std::uintptr_t>(expectedOutputs[resultIndex].getUserData()));
      |                                                                                                      ^~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>