Fix instances of -Wmissing-template-arg-list-after-template-kw
Clang has a new warning that requires a template argument list after using
the template keyword. Remove uses of the template keyword when we're not
specifying types.

See https://github.com/llvm/llvm-project/issues/94194 for the upstream
clang change.

With -Werror, this warning causes the build to fail:

    .../vulkancts/modules/vulkan/shaderexecutor/vktShaderBuiltinPrecisionTests.cpp:1084:72:
    error: a template argument list is expected after a name prefixed by
    the template keyword [-Wmissing-template-arg-list-after-template-kw]
     1084 |             const auto lo =
     FloatTypeSelector<GenType>::type::template
     convert(tcu::Float64(interval.lo()));
          |
          ^
    .../vulkancts/modules/vulkan/shaderexecutor/vktShaderBuiltinPrecisionTests.cpp:1091:72:
    error: a template argument list is expected after a name prefixed by
    the template keyword [-Wmissing-template-arg-list-after-template-kw]
     1091 |             const auto lo =
     FloatTypeSelector<GenType>::type::template
     convert(tcu::Float64(interval.lo()));
          |
          ^
    .../vulkancts/modules/vulkan/shaderexecutor/vktShaderBuiltinPrecisionTests.cpp:1092:72:
    error: a template argument list is expected after a name prefixed by
    the template keyword [-Wmissing-template-arg-list-after-template-kw]
     1092 |             const auto hi =
     FloatTypeSelector<GenType>::type::template
     convert(tcu::Float64(interval.hi()));
          |
          ^
    .../vulkancts/modules/vulkan/shaderexecutor/vktShaderBuiltinPrecisionTests.cpp:7051:64:
    error: a template argument list is expected after a name prefixed by
    the template keyword [-Wmissing-template-arg-list-after-template-kw]
     7051 |             outValues.push_back(SamplingT::SelectorT::template
     conv(val));
          |
          ^
    4 errors generated.