Include missing <cstdint>
This error is seen with gcc-13 where include headers are not implicitly
included [1]

Fixes errors e.g.
error: 'uint32_t' does not name a type

[1] https://www.gnu.org/software/gcc/gcc-13/porting_to.html

Signed-off-by: Khem Raj <raj.khem@gmail.com>