Add missing cmath includes
This fixes the compilation errors in chromium and ANGLE:

glcTextureStorageTests.cpp:76:35: error: no member named 'floor' in namespace 'std'
glcTextureStorageTests.cpp:76:46: error: no member named 'log2f' in namespace 'std'